"""Restricted Python execution for dataframe analytics.

This is an application-level guard, not a hardened OS/container sandbox. Generated
code is limited to dataframe analytics libraries and a small safe builtin set.
"""

import ast
import io
import sys
import re
from typing import Dict, Any, Optional

import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

try:
    import duckdb
except ImportError:  # DuckDB is optional for basic Pandas analysis.
    duckdb = None


class CodeInterpreter:
    """Execute generated analytics code with a restricted namespace."""

    DISALLOWED_MODULES = {
        "os", "subprocess", "shutil", "sys", "socket", "urllib", "requests",
        "pathlib", "importlib", "builtins", "ctypes", "multiprocessing",
        "pickle", "marshal", "shelve", "tempfile",
    }
    DISALLOWED_CALLS = {
        "eval", "exec", "compile", "open", "input", "help", "dir", "globals",
        "locals", "vars", "getattr", "setattr", "delattr", "__import__",
    }
    DISALLOWED_ATTRS = {
        "to_csv", "to_excel", "to_json", "to_pickle", "to_feather", "to_parquet",
        "to_sql", "read_csv", "read_excel", "read_json", "read_parquet",
        "read_feather", "read_pickle", "read_sql", "read_sql_query",
        "system", "popen", "run", "call", "check_output", "check_call",
        "__globals__", "__builtins__", "__subclasses__", "__bases__", "__mro__",
    }
    SAFE_BUILTINS = {
        "abs": abs, "all": all, "any": any, "bool": bool, "dict": dict,
        "enumerate": enumerate, "filter": filter, "float": float, "int": int,
        "len": len, "list": list, "map": map, "max": max, "min": min,
        "range": range, "round": round, "set": set, "sorted": sorted,
        "str": str, "sum": sum, "tuple": tuple, "zip": zip, "print": print,
        "isinstance": isinstance, "type": type,
    }

    @classmethod
    def clean_code(cls, raw_code: str) -> str:
        code = (raw_code or "").strip()
        match = re.search(r"```(?:python)?\s*([\s\S]*?)\s*```", code, re.IGNORECASE)
        return match.group(1).strip() if match else code

    @classmethod
    def check_safety(cls, code: str) -> Optional[str]:
        try:
            tree = ast.parse(code, mode="exec")
        except SyntaxError as exc:
            return f"Invalid Python generated by the model: {exc}"

        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    root = alias.name.split(".")[0]
                    if root in cls.DISALLOWED_MODULES:
                        return f"Execution blocked: Module '{root}' is restricted for security."
                    return "Execution blocked: imports are not permitted in generated analytics code."
            if isinstance(node, ast.ImportFrom):
                root = (node.module or "").split(".")[0]
                if root in cls.DISALLOWED_MODULES:
                    return f"Execution blocked: Module '{root}' is restricted for security."
                return "Execution blocked: imports are not permitted in generated analytics code."
            if isinstance(node, ast.Name) and node.id.startswith("__"):
                return "Execution blocked: dunder names are not permitted."
            if isinstance(node, ast.Attribute) and (node.attr in cls.DISALLOWED_ATTRS or node.attr.startswith("__")):
                return f"Execution blocked: Attribute '{node.attr}' is restricted for security."
            if isinstance(node, ast.Call) and isinstance(node.func, ast.Name) and node.func.id in cls.DISALLOWED_CALLS:
                return f"Execution blocked: Function '{node.func.id}' is restricted for security."
        return None

    @classmethod
    def execute(cls, code: str, df: pd.DataFrame) -> Dict[str, Any]:
        cleaned = cls.clean_code(code)
        safety_error = cls.check_safety(cleaned)
        if safety_error:
            return {"success": False, "stdout": "", "error": safety_error, "fig": None, "result_df": None, "code": cleaned}

        buffer = io.StringIO()
        local_scope: Dict[str, Any] = {
            "df": df.copy(deep=True), "pd": pd, "np": np, "px": px, "go": go,
            "fig": None, "result_df": None, "result": None,
            "duckdb": duckdb,
        }
        safe_globals = {"__builtins__": cls.SAFE_BUILTINS}
        original_stdout = sys.stdout
        try:
            sys.stdout = buffer
            exec(cleaned, safe_globals, local_scope)
            captured_stdout = buffer.getvalue()
            fig = local_scope.get("fig")
            if not isinstance(fig, (go.Figure, dict)):
                fig = None

            raw_res = local_scope.get("result_df")
            if raw_res is None:
                raw_res = local_scope.get("result")
            if isinstance(raw_res, pd.Series):
                raw_res = raw_res.to_frame()
            result_df = raw_res if isinstance(raw_res, pd.DataFrame) else None

            return {"success": True, "stdout": captured_stdout, "fig": fig, "result_df": result_df, "error": None, "code": cleaned}
        except Exception as exc:
            return {"success": False, "stdout": buffer.getvalue(), "fig": None, "result_df": None, "error": f"{type(exc).__name__}: {exc}", "code": cleaned}
        finally:
            sys.stdout = original_stdout
